### ISSUE TITLE
Single Approvals and Cross-Repo Approvers

### ISSUE THREAD

**Issue by jimbishopp** [gravitational/shared-workflows#205]
This issue describes two problems that require upgrading our internal review bot.

### Single Approvers
As our automation has matured, we have increased the number of pull requests required to upgrade our cloud platform. Many of these new pull requests are simple configuration changes - e.g. [bumping an image version](https://github.com/gravitational/cloud/pull/7106) or [changing a component's resource requirements](https://github.com/gravitational/cloud/pull/7150). **Since these PRs fall into our normal approval flow, they each require two approvals.** This requirement increases the number of reviews our engineers are required to perform and increases the time it takes to push a simple configuration change through to production.

To counter this inefficiency, we will upgrade the review bot to allow single approvers for specific repository paths. 

_While there is no audit requirement for two approvers, we do want to continue requiring two approvals for any code or platform change that isn't considered a simple configuration change._

### Cross-Repo Reviewers
Our cloud platform now hosts components that are primarily operated and maintained by core engineers. These components are configured in the cloud repo and deployed by cloud CD. The problem is that all pull requests submitted to the cloud repository are only reviewable by the cloud team. This is terribly inefficient. To resolve, the review bot should allow a single reviewer to review pull requests in both the cloud and core repositories.

### Examples
* The Core TAG team should be able to approve [bumping the TAG version](https://github.com/gravitational/cloud/pull/7111) without asking for reviews from the cloud team
* The Cloud Operations team should be able to [bump an image version](https://github.com/gravitational/cloud/pull/7106) without requiring two approvals.
* The Core Tooling team, who owns the Teleport release server, should be able to [make changes to their service](https://github.com/gravitational/cloud/pull/6972) without requiring a review from the cloud team.

**Comment by zmb3** [comment]
I support this plan and agree that core and cloud should be able to review each others changes in all repos. This has caused friction in a number of places (EUBP team can't approve cloud PRs, cloud growth team can't approve Teleport UI PRs, etc).

**Comment by jimbishopp** [comment]
https://github.com/gravitational/github-terraform/pull/755
